version: '3'
services:
  nginx:
    container_name: nginx
    #network_mode: "bridge"
    build:
      context: ../Nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/vestec/certs:/var/vestec/certs
      - ../Nginx/static/:/var/www/
    links:
      - website:website
    networks:
      - vestec

  website:
    container_name: website
    build:
      context: ../
      dockerfile: website/Dockerfile
    ports:
      - 8000:8000
    environment:
      VESTEC_MANAGER_URI: "http://manager:5500/jobs"
      VESTEC_EDI_URI: "http://manager:5501/EDImanager"
      JWT_PASSWD: "SECRET"  # to be replaced by docker secrets
    env_file:
      - environment_variables.env
    networks:
      - vestec

  manager:
    container_name: manager
    depends_on:
      - "maria"
    build:
      context: ../
      dockerfile: SimulationManager/Dockerfile
    #WE ONLY NEED THIS IF WE ARE USING SQLITE
    # volumes:
    #   - "../Database:/database"
    env_file:
      - environment_variables.env
    networks:
      - vestec

  maria:
    container_name: mariadb
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: "changeme"
    volumes:
      - "/var/vestec/db:/var/lib/mysql"
    networks:
      - vestec
    
      
  rmq:
    container_name: rabbitmq
    image: rabbitmq
    networks:
      - vestec
  
  workflow:
    container_name: workflowManager
    depends_on:
      - "rmq"
      - "maria"
    build:
      context: ../
      dockerfile: WorkflowManager/Dockerfile
    env_file:
      - environment_variables.env
    networks:
      - vestec
    

networks:
  vestec:
    driver: "bridge"
