version: '3'
services:
  nginx:
    container_name: nginx
    build:
      context: ../Nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"

  website:
    container_name: website
    build:
      context: ../
      dockerfile: DockerFiles/Dockerfile_website
    environment:
      VESTEC_MANAGER_URI: "http://manager:5500/jobs"

  manager:
    container_name: manager
    depends_on:
      - "maria"
    build:
      context: ../
      dockerfile: DockerFiles/Dockerfile_SimulationManager
    environment:
      # "mysql" or "sqlite"
      VESTEC_DB_TYPE: "mysql"
      # sqlite variables
      VESTEC_DB_PATH: "/database/vestec.sqlite"
      # mysql variables
      VESTEC_DB_USER: "root"
      VESTEC_DB_PASSWD: "changeme"
      VESTEC_DB_SERVER: "maria"
      VESTEC_DB_PORT: "3306"
      VESTEC_DB_NAME: "testdb"
    #WE ONLY NEED THIS IF WE ARE USING SQLITE
    # volumes:
    #   - "../Database:/database"

  maria:
    container_name: mariadb
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: "changeme"
    volumes:
      - "/scratch/db/:/var/lib/mysql"
